# Generated by Django 3.1.4 on 2021-01-02 10:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.BinaryField(editable=True)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_id', to='personal.personal')),
            ],
            options={
                'db_table': 'asistencia',
            },
        ),
    ]
