# Generated by Django 3.1.4 on 2021-01-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='imagen',
            field=models.TextField(),
        ),
    ]
