# Generated by Django 3.1.4 on 2021-01-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_auto_20210106_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='evento',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='tipoEvento',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
