# Generated by Django 3.1.4 on 2021-01-08 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_auto_20210108_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistencia',
            old_name='tipoEvento',
            new_name='tipo_evento',
        ),
    ]
